services:
  - type: web
    name: bitespeed-contact-reconciliation
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: contacts-db
      mountPath: /opt/render/project/src
      sizeGB: 1